apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: istio-proxy-metrics
  namespace: monitoring
  labels:
    app: istio-proxy
spec:
  selector:
    matchExpressions:
    - key: security.istio.io/tlsMode
      operator: Exists
  namespaceSelector:
    any: true
  jobLabel: istio-proxy
  podMetricsEndpoints:
  - path: /stats/prometheus
    interval: 15s
    scheme: http
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_container_name]
      action: keep
      regex: "istio-proxy"
    - sourceLabels: [__meta_kubernetes_pod_ip]
      action: replace
      targetLabel: __address__
      regex: (.+)
      replacement: $1:15020
          
