# argocd/applications/00-infra.yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # 가장 먼저
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.20.0
    chart: base
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.20.0
    chart: istiod
    helm:
      values: |
        pilot:
          autoscaleEnabled: false
          resources:
            requests:
              cpu: 200m      # 1000m → 200m로 대폭 줄임
              memory: 1024Mi # 4096Mi → 1024Mi로 대폭 줄임
            limits:
              cpu: 500m      # 2000m → 500m로 대폭 줄임
              memory: 2048Mi # 8192Mi → 2048Mi로 대폭 줄임
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingressgateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.20.0
    chart: gateway
    helm:
      releaseName: istio-ingressgateway
      values: |
        service:
          type: NodePort
          ports:
            - name: status-port
              port: 15021
              targetPort: 15021
              protocol: TCP
            - name: http2
              port: 80
              targetPort: 8080
              nodePort: 31541
              protocol: TCP
            - name: http-8081
              port: 8081
              targetPort: 9090
              nodePort: 31542
              protocol: TCP
            - name: monitoring
              port: 9090
              targetPort: 9090
              nodePort: 31544
              protocol: TCP
            - name: https
              port: 443
              targetPort: 8443
              nodePort: 31026
              protocol: TCP
        resources:
          requests:
            cpu: 200m        # 500m → 200m로 줄임
            memory: 512Mi    # 1024Mi → 512Mi로 줄임
          limits:
            cpu: 500m        # 1000m → 500m로 줄임
            memory: 1024Mi   # 2048Mi → 1024Mi로 줄임
        autoscaling:
          enabled: false     # true → false로 변경 (안정성 우선)
          minReplicas: 2
          maxReplicas: 5
          targetCPUUtilizationPercentage: 80
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 55.5.0
    chart: kube-prometheus-stack
    helm:
      values: |
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
            retention: 7d
            resources:
              requests:
                cpu: 200m      # 1000m → 200m로 줄임
                memory: 1024Mi # 4096Mi → 1024Mi로 줄임
              limits:
                cpu: 500m      # 2000m → 500m로 줄임
                memory: 2048Mi # 8192Mi → 2048Mi로 줄임
        grafana:
          adminPassword: admin123
          service:
            type: ClusterIP
          persistence:
            enabled: false
          resources:
            requests:
              cpu: 100m      # 500m → 100m로 줄임
              memory: 256Mi  # 1024Mi → 256Mi로 줄임
            limits:
              cpu: 300m      # 1000m → 300m로 줄임
              memory: 512Mi  # 2048Mi → 512Mi로 줄임
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://jaegertracing.github.io/helm-charts
    targetRevision: 0.71.0
    chart: jaeger
    helm:
      values: |
        provisionDataStore:
          cassandra: false
        allInOne:
          enabled: true
          args:  # ← 추가
            - "--query.base-path=/jaeger"
          resources:
            requests:
              cpu: 100m      # 500m → 100m로 줄임
              memory: 256Mi  # 1024Mi → 256Mi로 줄임
            limits:
              cpu: 300m      # 1000m → 300m로 줄임
              memory: 512Mi  # 2048Mi → 512Mi로 줄임
        storage:
          type: memory
        agent:
          enabled: false
        collector:
          enabled: false
        query:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kiali.org/helm-charts
    targetRevision: 1.77.0
    chart: kiali-server
    helm:
      values: |
        auth:
          strategy: anonymous
        external_services:
          prometheus:
            url: http://prometheus-kube-prometheus-prometheus.monitoring:9090
          grafana:
            url: http://prometheus-grafana.monitoring:80
          tracing:
            enabled: true
            namespace_selector: true
            url: http://jaeger-query.istio-system:16686
        deployment:
          ingress:
            enabled: false
          resources:
            requests:
              cpu: 100m      # 200m → 100m로 줄임
              memory: 256Mi  # 512Mi → 256Mi로 줄임
            limits:
              cpu: 300m      # 500m → 300m로 줄임
              memory: 512Mi  # 1024Mi → 512Mi로 줄임
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
