# argocd/applications/02-app-stack.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"  # DB 다음
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/xaczxzz/istio-helm-practice.git
    targetRevision: main
    path: helm/umbrella-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas