# argocd/applications/02-istio-gateway.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingressgateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.20.0
    chart: gateway
    helm:
      releaseName: istio-ingressgateway
      values: |
        service:
          type: LoadBalancer
          ports:
            - name: http
              port: 80
              targetPort: 8081
            - name: https
              port: 443
              targetPort: 8443
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true