# argocd/applications/02-jaeger.yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://jaegertracing.github.io/helm-charts
    targetRevision: 0.71.18
    chart: jaeger
    helm:
      values: |
        allInOne:
          enabled: true
          image: jaegertracing/all-in-one:1.57
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
        agent:
          enabled: false
        collector:
          enabled: false
        query:
          enabled: false
        cassandra:
          enabled: false
        elasticsearch:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true