# argocd/applications/02-jaeger.yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://jaegertracing.github.io/helm-charts
    targetRevision: 3.3.0
    chart: jaeger
    helm:
      values: |
        provisionDataStore:
          cassandra: false
          elasticsearch: false
        allInOne:
          enabled: true
          image: jaegertracing/all-in-one:1.57
          options:
            log-level: info
            memory.max-traces: 50000
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
        agent:
          enabled: false
        collector:
          enabled: false
        query:
          enabled: false
        # Service configuration
        allInOne:
          service:
            type: ClusterIP
            # Jaeger UI port
            query:
              port: 16686
            # Jaeger collector ports
            collector:
              http:
                port: 14268
              grpc:
                port: 14250
            # Jaeger agent ports
            agent:
              zipkinThrift:
                port: 5775
              compact:
                port: 6831
              binary:
                port: 6832
              http:
                port: 5778
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true