# # argocd/applications/02-jaeger.yaml
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: jaeger
#   namespace: argocd
#   annotations:
#     argocd.argoproj.io/sync-wave: "3"
# spec:
#   project: default
#   source:
#     repoURL: https://jaegertracing.github.io/helm-charts
#     targetRevision: 3.3.0
#     chart: jaeger
#     helm:
#       values: |
#         provisionDataStore:
#           cassandra: false
#           elasticsearch: false
#         allInOne:
#           enabled: true
#           image:
#             registry: docker.io
#             repository: jaegertracing/all-in-one
#             tag: "1.57"
#             pullPolicy: IfNotPresent
#           options:
#             log-level: info
#             memory.max-traces: 50000
#           storage:
#             type: memory  # 이 줄 추가!
#           resources:
#             requests:
#               cpu: 100m
#               memory: 256Mi
#             limits:
#               cpu: 500m
#               memory: 512Mi
#           service:
#             type: ClusterIP
#             query:
#               port: 16686
#             collector:
#               http:
#                 port: 14268
#               grpc:
#                 port: 14250
#             agent:
#               zipkinThrift:
#                 port: 5775
#               compact:
#                 port: 6831
#               binary:
#                 port: 6832
#               http:
#                 port: 5778
#         agent:
#           enabled: false
#         collector:
#           enabled: false
#         query:
#           enabled: false
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: istio-system
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true