# argocd/applications/04-observability.yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kiali.org/helm-charts
    targetRevision: 1.77.0
    chart: kiali-server
    helm:
      values: |
        auth:
          strategy: anonymous
        external_services:
          prometheus:
            url: http://prometheus-kube-prometheus-prometheus.monitoring:9090
          grafana:
            url: http://prometheus-grafana.monitoring:80
          tracing:
            enabled: true
            namespace_selector: true
            url: http://jaeger-query.istio-system:16686
        deployment:
          ingress:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://jaegertracing.github.io/helm-charts
    targetRevision: 0.71.0
    chart: jaeger
    helm:
      values: |
        provisionDataStore:
          cassandra: false
        allInOne:
          enabled: true
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
        storage:
          type: memory
        agent:
          enabled: false
        collector:
          enabled: false
        query:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true