# Istio configuration application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-config
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/xaczxzz/istio-helm-practice.git
    targetRevision: main
    path: k8s/istio
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  # Sync waves to ensure proper order
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true